//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Clan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Clan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NazivClana" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RedniBrojClana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SimbolickiNazivClana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StavClana" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TekstStava" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TackaStavaClana" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RedniBrojTacke" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="TekstTacke" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Podtacka" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RedniBrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TekstPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Clan", propOrder = {
    "nazivClana",
    "redniBrojClana",
    "simbolickiNazivClana",
    "stavClana"
})
public class Clan {

    @XmlElement(name = "NazivClana")
    protected String nazivClana;
    @XmlElement(name = "RedniBrojClana", required = true)
    protected String redniBrojClana;
    @XmlElement(name = "SimbolickiNazivClana", required = true)
    protected String simbolickiNazivClana;
    @XmlElement(name = "StavClana", required = true)
    protected List<Clan.StavClana> stavClana;

    /**
     * Gets the value of the nazivClana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivClana() {
        return nazivClana;
    }

    /**
     * Sets the value of the nazivClana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivClana(String value) {
        this.nazivClana = value;
    }

    /**
     * Gets the value of the redniBrojClana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedniBrojClana() {
        return redniBrojClana;
    }

    /**
     * Sets the value of the redniBrojClana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedniBrojClana(String value) {
        this.redniBrojClana = value;
    }

    /**
     * Gets the value of the simbolickiNazivClana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNazivClana() {
        return simbolickiNazivClana;
    }

    /**
     * Sets the value of the simbolickiNazivClana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNazivClana(String value) {
        this.simbolickiNazivClana = value;
    }

    /**
     * Gets the value of the stavClana property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavClana property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavClana().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Clan.StavClana }
     * 
     * 
     */
    public List<Clan.StavClana> getStavClana() {
        if (stavClana == null) {
            stavClana = new ArrayList<Clan.StavClana>();
        }
        return this.stavClana;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TekstStava" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TackaStavaClana" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RedniBrojTacke" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="TekstTacke" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Podtacka" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RedniBrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TekstPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tekstStava",
        "tackaStavaClana"
    })
    public static class StavClana {

        @XmlElement(name = "TekstStava", required = true)
        protected String tekstStava;
        @XmlElement(name = "TackaStavaClana")
        protected List<Clan.StavClana.TackaStavaClana> tackaStavaClana;

        /**
         * Gets the value of the tekstStava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekstStava() {
            return tekstStava;
        }

        /**
         * Sets the value of the tekstStava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekstStava(String value) {
            this.tekstStava = value;
        }

        /**
         * Gets the value of the tackaStavaClana property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tackaStavaClana property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTackaStavaClana().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Clan.StavClana.TackaStavaClana }
         * 
         * 
         */
        public List<Clan.StavClana.TackaStavaClana> getTackaStavaClana() {
            if (tackaStavaClana == null) {
                tackaStavaClana = new ArrayList<Clan.StavClana.TackaStavaClana>();
            }
            return this.tackaStavaClana;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RedniBrojTacke" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="TekstTacke" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Podtacka" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RedniBrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TekstPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "redniBrojTacke",
            "tekstTacke",
            "podtacka"
        })
        public static class TackaStavaClana {

            @XmlElement(name = "RedniBrojTacke", required = true)
            protected BigInteger redniBrojTacke;
            @XmlElement(name = "TekstTacke", required = true)
            protected String tekstTacke;
            @XmlElement(name = "Podtacka")
            protected List<Clan.StavClana.TackaStavaClana.Podtacka> podtacka;

            /**
             * Gets the value of the redniBrojTacke property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRedniBrojTacke() {
                return redniBrojTacke;
            }

            /**
             * Sets the value of the redniBrojTacke property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRedniBrojTacke(BigInteger value) {
                this.redniBrojTacke = value;
            }

            /**
             * Gets the value of the tekstTacke property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTekstTacke() {
                return tekstTacke;
            }

            /**
             * Sets the value of the tekstTacke property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTekstTacke(String value) {
                this.tekstTacke = value;
            }

            /**
             * Gets the value of the podtacka property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the podtacka property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPodtacka().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Clan.StavClana.TackaStavaClana.Podtacka }
             * 
             * 
             */
            public List<Clan.StavClana.TackaStavaClana.Podtacka> getPodtacka() {
                if (podtacka == null) {
                    podtacka = new ArrayList<Clan.StavClana.TackaStavaClana.Podtacka>();
                }
                return this.podtacka;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RedniBrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TekstPodtacke" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "redniBrojPodtacke",
                "tekstPodtacke",
                "alineja"
            })
            public static class Podtacka {

                @XmlElement(name = "RedniBrojPodtacke", required = true)
                protected Object redniBrojPodtacke;
                @XmlElement(name = "TekstPodtacke", required = true)
                protected Object tekstPodtacke;
                @XmlElement(name = "Alineja")
                protected List<String> alineja;

                /**
                 * Gets the value of the redniBrojPodtacke property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getRedniBrojPodtacke() {
                    return redniBrojPodtacke;
                }

                /**
                 * Sets the value of the redniBrojPodtacke property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setRedniBrojPodtacke(Object value) {
                    this.redniBrojPodtacke = value;
                }

                /**
                 * Gets the value of the tekstPodtacke property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTekstPodtacke() {
                    return tekstPodtacke;
                }

                /**
                 * Sets the value of the tekstPodtacke property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTekstPodtacke(Object value) {
                    this.tekstPodtacke = value;
                }

                /**
                 * Gets the value of the alineja property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the alineja property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAlineja().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getAlineja() {
                    if (alineja == null) {
                        alineja = new ArrayList<String>();
                    }
                    return this.alineja;
                }

            }

        }

    }

}
