//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 01:07:20 PM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="simbolickiNaziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;choice>
 *             &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="stav" maxOccurs="unbounded">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                       &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                       &lt;element name="tacka" maxOccurs="unbounded" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                 &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                 &lt;element name="podtacka" maxOccurs="unbounded" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                           &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                           &lt;element name="alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clan", propOrder = {
    "naziv",
    "redniBroj",
    "simbolickiNaziv",
    "tekstOrStav"
})
public class Clan {

    protected String naziv;
    protected int redniBroj;
    @XmlElement(required = true)
    protected String simbolickiNaziv;
    @XmlElements({
        @XmlElement(name = "tekst", type = String.class),
        @XmlElement(name = "stav", type = Clan.Stav.class)
    })
    protected List<Object> tekstOrStav;

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the redniBroj property.
     * 
     */
    public int getRedniBroj() {
        return redniBroj;
    }

    /**
     * Sets the value of the redniBroj property.
     * 
     */
    public void setRedniBroj(int value) {
        this.redniBroj = value;
    }

    /**
     * Gets the value of the simbolickiNaziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNaziv() {
        return simbolickiNaziv;
    }

    /**
     * Sets the value of the simbolickiNaziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNaziv(String value) {
        this.simbolickiNaziv = value;
    }

    /**
     * Gets the value of the tekstOrStav property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tekstOrStav property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTekstOrStav().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link Clan.Stav }
     * 
     * 
     */
    public List<Object> getTekstOrStav() {
        if (tekstOrStav == null) {
            tekstOrStav = new ArrayList<Object>();
        }
        return this.tekstOrStav;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tacka" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="podtacka" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "redniBroj",
        "tekst",
        "tacka"
    })
    public static class Stav {

        @XmlElement(required = true)
        protected BigInteger redniBroj;
        @XmlElement(required = true)
        protected String tekst;
        protected List<Clan.Stav.Tacka> tacka;

        /**
         * Gets the value of the redniBroj property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRedniBroj() {
            return redniBroj;
        }

        /**
         * Sets the value of the redniBroj property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRedniBroj(BigInteger value) {
            this.redniBroj = value;
        }

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekst(String value) {
            this.tekst = value;
        }

        /**
         * Gets the value of the tacka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tacka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTacka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Clan.Stav.Tacka }
         * 
         * 
         */
        public List<Clan.Stav.Tacka> getTacka() {
            if (tacka == null) {
                tacka = new ArrayList<Clan.Stav.Tacka>();
            }
            return this.tacka;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="podtacka" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "redniBroj",
            "tekst",
            "podtacka"
        })
        public static class Tacka {

            @XmlElement(required = true)
            protected BigInteger redniBroj;
            @XmlElement(required = true)
            protected String tekst;
            protected List<Clan.Stav.Tacka.Podtacka> podtacka;

            /**
             * Gets the value of the redniBroj property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRedniBroj() {
                return redniBroj;
            }

            /**
             * Sets the value of the redniBroj property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRedniBroj(BigInteger value) {
                this.redniBroj = value;
            }

            /**
             * Gets the value of the tekst property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTekst() {
                return tekst;
            }

            /**
             * Sets the value of the tekst property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTekst(String value) {
                this.tekst = value;
            }

            /**
             * Gets the value of the podtacka property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the podtacka property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPodtacka().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Clan.Stav.Tacka.Podtacka }
             * 
             * 
             */
            public List<Clan.Stav.Tacka.Podtacka> getPodtacka() {
                if (podtacka == null) {
                    podtacka = new ArrayList<Clan.Stav.Tacka.Podtacka>();
                }
                return this.podtacka;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="alineja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "redniBroj",
                "tekst",
                "alineja"
            })
            public static class Podtacka {

                @XmlElement(required = true)
                protected BigInteger redniBroj;
                @XmlElement(required = true)
                protected String tekst;
                protected List<String> alineja;

                /**
                 * Gets the value of the redniBroj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getRedniBroj() {
                    return redniBroj;
                }

                /**
                 * Sets the value of the redniBroj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setRedniBroj(BigInteger value) {
                    this.redniBroj = value;
                }

                /**
                 * Gets the value of the tekst property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTekst() {
                    return tekst;
                }

                /**
                 * Sets the value of the tekst property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTekst(String value) {
                    this.tekst = value;
                }

                /**
                 * Gets the value of the alineja property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the alineja property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAlineja().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getAlineja() {
                    if (alineja == null) {
                        alineja = new ArrayList<String>();
                    }
                    return this.alineja;
                }

            }

        }

    }

}
