//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Deo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RedniBrojDela" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SimbolickiNazivDela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivDela" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
 *         &lt;element name="Glava" type="{http://www.ftn.uns.ac.rs/pravniAkt}Glava"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deo", propOrder = {
    "redniBrojDela",
    "simbolickiNazivDela",
    "nazivDela",
    "glava"
})
@XmlSeeAlso({
    UvodniDeo.class,
    GlavniDeo.class,
    ZavrsniDeo.class
})
public abstract class Deo {

    @XmlElement(name = "RedniBrojDela", required = true)
    protected BigInteger redniBrojDela;
    @XmlElement(name = "SimbolickiNazivDela", required = true)
    protected String simbolickiNazivDela;
    @XmlElement(name = "NazivDela", required = true, nillable = true)
    protected String nazivDela;
    @XmlElement(name = "Glava", required = true)
    protected Glava glava;

    /**
     * Gets the value of the redniBrojDela property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBrojDela() {
        return redniBrojDela;
    }

    /**
     * Sets the value of the redniBrojDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBrojDela(BigInteger value) {
        this.redniBrojDela = value;
    }

    /**
     * Gets the value of the simbolickiNazivDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNazivDela() {
        return simbolickiNazivDela;
    }

    /**
     * Sets the value of the simbolickiNazivDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNazivDela(String value) {
        this.simbolickiNazivDela = value;
    }

    /**
     * Gets the value of the nazivDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDela() {
        return nazivDela;
    }

    /**
     * Sets the value of the nazivDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDela(String value) {
        this.nazivDela = value;
    }

    /**
     * Gets the value of the glava property.
     * 
     * @return
     *     possible object is
     *     {@link Glava }
     *     
     */
    public Glava getGlava() {
        return glava;
    }

    /**
     * Sets the value of the glava property.
     * 
     * @param value
     *     allowed object is
     *     {@link Glava }
     *     
     */
    public void setGlava(Glava value) {
        this.glava = value;
    }

}
