//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Glava complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Glava">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RedniBrojGlave" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SimbolickiNazivGlave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivGlave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OdeljakIliClan" type="{http://www.ftn.uns.ac.rs/pravniAkt}OdeljakIliClan" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipOznacavanjaGlave">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="bezTacke"/>
 *             &lt;enumeration value="saTackom"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Glava", propOrder = {
    "redniBrojGlave",
    "simbolickiNazivGlave",
    "nazivGlave",
    "odeljakIliClan"
})
public class Glava {

    @XmlElement(name = "RedniBrojGlave", required = true)
    protected BigInteger redniBrojGlave;
    @XmlElement(name = "SimbolickiNazivGlave", required = true)
    protected String simbolickiNazivGlave;
    @XmlElement(name = "NazivGlave", required = true)
    protected String nazivGlave;
    @XmlElement(name = "OdeljakIliClan", required = true)
    protected List<OdeljakIliClan> odeljakIliClan;
    @XmlAttribute(name = "tipOznacavanjaGlave")
    protected String tipOznacavanjaGlave;

    /**
     * Gets the value of the redniBrojGlave property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBrojGlave() {
        return redniBrojGlave;
    }

    /**
     * Sets the value of the redniBrojGlave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBrojGlave(BigInteger value) {
        this.redniBrojGlave = value;
    }

    /**
     * Gets the value of the simbolickiNazivGlave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNazivGlave() {
        return simbolickiNazivGlave;
    }

    /**
     * Sets the value of the simbolickiNazivGlave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNazivGlave(String value) {
        this.simbolickiNazivGlave = value;
    }

    /**
     * Gets the value of the nazivGlave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivGlave() {
        return nazivGlave;
    }

    /**
     * Sets the value of the nazivGlave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivGlave(String value) {
        this.nazivGlave = value;
    }

    /**
     * Gets the value of the odeljakIliClan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the odeljakIliClan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOdeljakIliClan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OdeljakIliClan }
     * 
     * 
     */
    public List<OdeljakIliClan> getOdeljakIliClan() {
        if (odeljakIliClan == null) {
            odeljakIliClan = new ArrayList<OdeljakIliClan>();
        }
        return this.odeljakIliClan;
    }

    /**
     * Gets the value of the tipOznacavanjaGlave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipOznacavanjaGlave() {
        return tipOznacavanjaGlave;
    }

    /**
     * Sets the value of the tipOznacavanjaGlave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipOznacavanjaGlave(String value) {
        this.tipOznacavanjaGlave = value;
    }

}
