//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 04:06:37 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.pravniakt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeoNaziv_QNAME = new QName("http://www.ftn.uns.ac.rs/pravniAkt", "naziv");
    private final static QName _DeoRedniBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/pravniAkt", "redniBroj");
    private final static QName _DeoSimbolickiNaziv_QNAME = new QName("http://www.ftn.uns.ac.rs/pravniAkt", "simbolickiNaziv");
    private final static QName _ClanTekstClan_QNAME = new QName("http://www.ftn.uns.ac.rs/pravniAkt", "clan");
    private final static QName _PododeljakRednoSlovo_QNAME = new QName("http://www.ftn.uns.ac.rs/pravniAkt", "rednoSlovo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.pravniakt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Clan.Stav }
     * 
     */
    public Clan.Stav createClanStav() {
        return new Clan.Stav();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka }
     * 
     */
    public Clan.Stav.Tacka createClanStavTacka() {
        return new Clan.Stav.Tacka();
    }

    /**
     * Create an instance of {@link Propis }
     * 
     */
    public Propis createPropis() {
        return new Propis();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link Odeljak }
     * 
     */
    public Odeljak createOdeljak() {
        return new Odeljak();
    }

    /**
     * Create an instance of {@link Prilog }
     * 
     */
    public Prilog createPrilog() {
        return new Prilog();
    }

    /**
     * Create an instance of {@link Pododeljak }
     * 
     */
    public Pododeljak createPododeljak() {
        return new Pododeljak();
    }

    /**
     * Create an instance of {@link Glava }
     * 
     */
    public Glava createGlava() {
        return new Glava();
    }

    /**
     * Create an instance of {@link Clan.Tekst }
     * 
     */
    public Clan.Tekst createClanTekst() {
        return new Clan.Tekst();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka }
     * 
     */
    public Clan.Stav.Tacka.Podtacka createClanStavTackaPodtacka() {
        return new Clan.Stav.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "naziv", scope = Deo.class)
    public JAXBElement<String> createDeoNaziv(String value) {
        return new JAXBElement<String>(_DeoNaziv_QNAME, String.class, Deo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "redniBroj", scope = Deo.class)
    public JAXBElement<BigInteger> createDeoRedniBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_DeoRedniBroj_QNAME, BigInteger.class, Deo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "simbolickiNaziv", scope = Deo.class)
    public JAXBElement<String> createDeoSimbolickiNaziv(String value) {
        return new JAXBElement<String>(_DeoSimbolickiNaziv_QNAME, String.class, Deo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "clan", scope = Clan.Tekst.class)
    public JAXBElement<Integer> createClanTekstClan(Integer value) {
        return new JAXBElement<Integer>(_ClanTekstClan_QNAME, Integer.class, Clan.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "naziv", scope = Pododeljak.class)
    public JAXBElement<String> createPododeljakNaziv(String value) {
        return new JAXBElement<String>(_DeoNaziv_QNAME, String.class, Pododeljak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "rednoSlovo", scope = Pododeljak.class)
    public JAXBElement<String> createPododeljakRednoSlovo(String value) {
        return new JAXBElement<String>(_PododeljakRednoSlovo_QNAME, String.class, Pododeljak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "naziv", scope = Glava.class)
    public JAXBElement<String> createGlavaNaziv(String value) {
        return new JAXBElement<String>(_DeoNaziv_QNAME, String.class, Glava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "redniBroj", scope = Glava.class)
    public JAXBElement<BigInteger> createGlavaRedniBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_DeoRedniBroj_QNAME, BigInteger.class, Glava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "simbolickiNaziv", scope = Glava.class)
    public JAXBElement<String> createGlavaSimbolickiNaziv(String value) {
        return new JAXBElement<String>(_DeoSimbolickiNaziv_QNAME, String.class, Glava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "naziv", scope = Odeljak.class)
    public JAXBElement<String> createOdeljakNaziv(String value) {
        return new JAXBElement<String>(_DeoNaziv_QNAME, String.class, Odeljak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "redniBroj", scope = Odeljak.class)
    public JAXBElement<BigInteger> createOdeljakRedniBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_DeoRedniBroj_QNAME, BigInteger.class, Odeljak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/pravniAkt", name = "simbolickiNaziv", scope = Odeljak.class)
    public JAXBElement<String> createOdeljakSimbolickiNaziv(String value) {
        return new JAXBElement<String>(_DeoSimbolickiNaziv_QNAME, String.class, Odeljak.class, value);
    }

}
