//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OdeljakIliClan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OdeljakIliClan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Clan" type="{http://www.ftn.uns.ac.rs/pravniAkt}Clan"/>
 *         &lt;element name="Odeljak" type="{http://www.ftn.uns.ac.rs/pravniAkt}Odeljak"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OdeljakIliClan", propOrder = {
    "clan",
    "odeljak"
})
public class OdeljakIliClan {

    @XmlElement(name = "Clan")
    protected Clan clan;
    @XmlElement(name = "Odeljak")
    protected Odeljak odeljak;

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link Clan }
     *     
     */
    public Clan getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clan }
     *     
     */
    public void setClan(Clan value) {
        this.clan = value;
    }

    /**
     * Gets the value of the odeljak property.
     * 
     * @return
     *     possible object is
     *     {@link Odeljak }
     *     
     */
    public Odeljak getOdeljak() {
        return odeljak;
    }

    /**
     * Sets the value of the odeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odeljak }
     *     
     */
    public void setOdeljak(Odeljak value) {
        this.odeljak = value;
    }

}
