//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Odeljak complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Odeljak">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RedniBrojOdeljka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SimbolickiNazivOdeljka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivOdeljka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PododeljakOdsekIliClan" type="{http://www.ftn.uns.ac.rs/pravniAkt}PododeljakOdsekIliClan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Odeljak", propOrder = {
    "redniBrojOdeljka",
    "simbolickiNazivOdeljka",
    "nazivOdeljka",
    "pododeljakOdsekIliClan"
})
public class Odeljak {

    @XmlElement(name = "RedniBrojOdeljka", required = true)
    protected BigInteger redniBrojOdeljka;
    @XmlElement(name = "SimbolickiNazivOdeljka", required = true)
    protected String simbolickiNazivOdeljka;
    @XmlElement(name = "NazivOdeljka", required = true)
    protected String nazivOdeljka;
    @XmlElement(name = "PododeljakOdsekIliClan", required = true)
    protected PododeljakOdsekIliClan pododeljakOdsekIliClan;

    /**
     * Gets the value of the redniBrojOdeljka property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBrojOdeljka() {
        return redniBrojOdeljka;
    }

    /**
     * Sets the value of the redniBrojOdeljka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBrojOdeljka(BigInteger value) {
        this.redniBrojOdeljka = value;
    }

    /**
     * Gets the value of the simbolickiNazivOdeljka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNazivOdeljka() {
        return simbolickiNazivOdeljka;
    }

    /**
     * Sets the value of the simbolickiNazivOdeljka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNazivOdeljka(String value) {
        this.simbolickiNazivOdeljka = value;
    }

    /**
     * Gets the value of the nazivOdeljka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivOdeljka() {
        return nazivOdeljka;
    }

    /**
     * Sets the value of the nazivOdeljka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivOdeljka(String value) {
        this.nazivOdeljka = value;
    }

    /**
     * Gets the value of the pododeljakOdsekIliClan property.
     * 
     * @return
     *     possible object is
     *     {@link PododeljakOdsekIliClan }
     *     
     */
    public PododeljakOdsekIliClan getPododeljakOdsekIliClan() {
        return pododeljakOdsekIliClan;
    }

    /**
     * Sets the value of the pododeljakOdsekIliClan property.
     * 
     * @param value
     *     allowed object is
     *     {@link PododeljakOdsekIliClan }
     *     
     */
    public void setPododeljakOdsekIliClan(PododeljakOdsekIliClan value) {
        this.pododeljakOdsekIliClan = value;
    }

}
