//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Odsek complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Odsek">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RedniBrojOdseka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SimbolickiNazivOdseka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivOdseka" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Clan" type="{http://www.ftn.uns.ac.rs/pravniAkt}Clan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Odsek", propOrder = {
    "redniBrojOdseka",
    "simbolickiNazivOdseka",
    "nazivOdseka",
    "clan"
})
public class Odsek {

    @XmlElement(name = "RedniBrojOdseka", required = true)
    protected BigInteger redniBrojOdseka;
    @XmlElement(name = "SimbolickiNazivOdseka", required = true)
    protected String simbolickiNazivOdseka;
    @XmlElement(name = "NazivOdseka", required = true)
    protected Object nazivOdseka;
    @XmlElement(name = "Clan", required = true)
    protected Clan clan;

    /**
     * Gets the value of the redniBrojOdseka property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBrojOdseka() {
        return redniBrojOdseka;
    }

    /**
     * Sets the value of the redniBrojOdseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBrojOdseka(BigInteger value) {
        this.redniBrojOdseka = value;
    }

    /**
     * Gets the value of the simbolickiNazivOdseka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimbolickiNazivOdseka() {
        return simbolickiNazivOdseka;
    }

    /**
     * Sets the value of the simbolickiNazivOdseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimbolickiNazivOdseka(String value) {
        this.simbolickiNazivOdseka = value;
    }

    /**
     * Gets the value of the nazivOdseka property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNazivOdseka() {
        return nazivOdseka;
    }

    /**
     * Sets the value of the nazivOdseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNazivOdseka(Object value) {
        this.nazivOdseka = value;
    }

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link Clan }
     *     
     */
    public Clan getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clan }
     *     
     */
    public void setClan(Clan value) {
        this.clan = value;
    }

}
