//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PododeljakOdsekIliClan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PododeljakOdsekIliClan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Clan" type="{http://www.ftn.uns.ac.rs/pravniAkt}Clan"/>
 *         &lt;element name="Pododeljak" type="{http://www.ftn.uns.ac.rs/pravniAkt}Pododeljak"/>
 *         &lt;element name="Odsek" type="{http://www.ftn.uns.ac.rs/pravniAkt}Odsek"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PododeljakOdsekIliClan", propOrder = {
    "clan",
    "pododeljak",
    "odsek"
})
public class PododeljakOdsekIliClan {

    @XmlElement(name = "Clan")
    protected Clan clan;
    @XmlElement(name = "Pododeljak")
    protected Pododeljak pododeljak;
    @XmlElement(name = "Odsek")
    protected Odsek odsek;

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link Clan }
     *     
     */
    public Clan getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clan }
     *     
     */
    public void setClan(Clan value) {
        this.clan = value;
    }

    /**
     * Gets the value of the pododeljak property.
     * 
     * @return
     *     possible object is
     *     {@link Pododeljak }
     *     
     */
    public Pododeljak getPododeljak() {
        return pododeljak;
    }

    /**
     * Sets the value of the pododeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pododeljak }
     *     
     */
    public void setPododeljak(Pododeljak value) {
        this.pododeljak = value;
    }

    /**
     * Gets the value of the odsek property.
     * 
     * @return
     *     possible object is
     *     {@link Odsek }
     *     
     */
    public Odsek getOdsek() {
        return odsek;
    }

    /**
     * Sets the value of the odsek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odsek }
     *     
     */
    public void setOdsek(Odsek value) {
        this.odsek = value;
    }

}
