//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pododeljak complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pododeljak">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RednoSlovoPododeljka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivPododeljka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Clan" type="{http://www.ftn.uns.ac.rs/pravniAkt}Clan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pododeljak", propOrder = {
    "rednoSlovoPododeljka",
    "nazivPododeljka",
    "clan"
})
public class Pododeljak {

    @XmlElement(name = "RednoSlovoPododeljka", required = true)
    protected String rednoSlovoPododeljka;
    @XmlElement(name = "NazivPododeljka", required = true)
    protected String nazivPododeljka;
    @XmlElement(name = "Clan", required = true)
    protected Clan clan;

    /**
     * Gets the value of the rednoSlovoPododeljka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRednoSlovoPododeljka() {
        return rednoSlovoPododeljka;
    }

    /**
     * Sets the value of the rednoSlovoPododeljka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRednoSlovoPododeljka(String value) {
        this.rednoSlovoPododeljka = value;
    }

    /**
     * Gets the value of the nazivPododeljka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPododeljka() {
        return nazivPododeljka;
    }

    /**
     * Sets the value of the nazivPododeljka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPododeljka(String value) {
        this.nazivPododeljka = value;
    }

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link Clan }
     *     
     */
    public Clan getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clan }
     *     
     */
    public void setClan(Clan value) {
        this.clan = value;
    }

}
