//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:20:41 AM CEST 
//


package rs.ac.uns.ftn.pravniakt;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UvodniDeo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UvodniDeo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ftn.uns.ac.rs/pravniAkt}Deo">
 *       &lt;sequence>
 *         &lt;element name="PredmetUredjivanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Definicija" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipUvodnogDela">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="saNacelima"/>
 *             &lt;enumeration value="bezNacela"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UvodniDeo", propOrder = {
    "predmetUredjivanja",
    "definicija"
})
public class UvodniDeo
    extends Deo
{

    @XmlElement(name = "PredmetUredjivanja", required = true)
    protected String predmetUredjivanja;
    @XmlElement(name = "Definicija")
    protected List<String> definicija;
    @XmlAttribute(name = "tipUvodnogDela")
    protected String tipUvodnogDela;

    /**
     * Gets the value of the predmetUredjivanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredmetUredjivanja() {
        return predmetUredjivanja;
    }

    /**
     * Sets the value of the predmetUredjivanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredmetUredjivanja(String value) {
        this.predmetUredjivanja = value;
    }

    /**
     * Gets the value of the definicija property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the definicija property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefinicija().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDefinicija() {
        if (definicija == null) {
            definicija = new ArrayList<String>();
        }
        return this.definicija;
    }

    /**
     * Gets the value of the tipUvodnogDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipUvodnogDela() {
        return tipUvodnogDela;
    }

    /**
     * Sets the value of the tipUvodnogDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipUvodnogDela(String value) {
        this.tipUvodnogDela = value;
    }

}
