//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:41:26 AM CEST 
//


package rs.ac.uns.ftn.amandman;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oznaka" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="zaglavlje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="drzava" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="organ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="predlagac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uvod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence>
 *                     &lt;choice>
 *                       &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                       &lt;element name="propis">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/choice>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="glavniDeo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sadrzaj">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tekst">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;choice>
 *                                         &lt;element name="deo" type="{http://www.ftn.uns.ac.rs/amandman}deo"/>
 *                                         &lt;element name="glava" type="{http://www.ftn.uns.ac.rs/amandman}glava"/>
 *                                         &lt;element name="odeljak" type="{http://www.ftn.uns.ac.rs/amandman}odeljak"/>
 *                                         &lt;element name="pododeljak" type="{http://www.ftn.uns.ac.rs/amandman}pododeljak"/>
 *                                         &lt;element name="clan" type="{http://www.ftn.uns.ac.rs/amandman}clan"/>
 *                                         &lt;element name="stav" type="{http://www.ftn.uns.ac.rs/amandman}stav"/>
 *                                         &lt;element name="tacka" type="{http://www.ftn.uns.ac.rs/amandman}tacka"/>
 *                                         &lt;element name="podtacka" type="{http://www.ftn.uns.ac.rs/amandman}podtacka"/>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="obrazlozenje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="potpis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="funkcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="imeIPrezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oznaka",
    "zaglavlje",
    "uvod",
    "glavniDeo",
    "obrazlozenje",
    "potpis"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    protected int oznaka;
    @XmlElement(required = true)
    protected Amandman.Zaglavlje zaglavlje;
    @XmlElement(required = true)
    protected Amandman.Uvod uvod;
    @XmlElement(required = true)
    protected Amandman.GlavniDeo glavniDeo;
    @XmlElement(required = true)
    protected Amandman.Obrazlozenje obrazlozenje;
    @XmlElement(required = true)
    protected Amandman.Potpis potpis;

    /**
     * Gets the value of the oznaka property.
     * 
     */
    public int getOznaka() {
        return oznaka;
    }

    /**
     * Sets the value of the oznaka property.
     * 
     */
    public void setOznaka(int value) {
        this.oznaka = value;
    }

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Zaglavlje }
     *     
     */
    public Amandman.Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Zaglavlje }
     *     
     */
    public void setZaglavlje(Amandman.Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the uvod property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Uvod }
     *     
     */
    public Amandman.Uvod getUvod() {
        return uvod;
    }

    /**
     * Sets the value of the uvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Uvod }
     *     
     */
    public void setUvod(Amandman.Uvod value) {
        this.uvod = value;
    }

    /**
     * Gets the value of the glavniDeo property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.GlavniDeo }
     *     
     */
    public Amandman.GlavniDeo getGlavniDeo() {
        return glavniDeo;
    }

    /**
     * Sets the value of the glavniDeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.GlavniDeo }
     *     
     */
    public void setGlavniDeo(Amandman.GlavniDeo value) {
        this.glavniDeo = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public Amandman.Obrazlozenje getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public void setObrazlozenje(Amandman.Obrazlozenje value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Potpis }
     *     
     */
    public Amandman.Potpis getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Potpis }
     *     
     */
    public void setPotpis(Amandman.Potpis value) {
        this.potpis = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sadrzaj">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tekst">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;choice>
     *                               &lt;element name="deo" type="{http://www.ftn.uns.ac.rs/amandman}deo"/>
     *                               &lt;element name="glava" type="{http://www.ftn.uns.ac.rs/amandman}glava"/>
     *                               &lt;element name="odeljak" type="{http://www.ftn.uns.ac.rs/amandman}odeljak"/>
     *                               &lt;element name="pododeljak" type="{http://www.ftn.uns.ac.rs/amandman}pododeljak"/>
     *                               &lt;element name="clan" type="{http://www.ftn.uns.ac.rs/amandman}clan"/>
     *                               &lt;element name="stav" type="{http://www.ftn.uns.ac.rs/amandman}stav"/>
     *                               &lt;element name="tacka" type="{http://www.ftn.uns.ac.rs/amandman}tacka"/>
     *                               &lt;element name="podtacka" type="{http://www.ftn.uns.ac.rs/amandman}podtacka"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "sadrzaj"
    })
    public static class GlavniDeo {

        @XmlElement(required = true, defaultValue = "\u0410\u041c\u0410\u041d\u0414\u041c\u0410\u041d")
        protected String naslov;
        @XmlElement(required = true)
        protected Amandman.GlavniDeo.Sadrzaj sadrzaj;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the sadrzaj property.
         * 
         * @return
         *     possible object is
         *     {@link Amandman.GlavniDeo.Sadrzaj }
         *     
         */
        public Amandman.GlavniDeo.Sadrzaj getSadrzaj() {
            return sadrzaj;
        }

        /**
         * Sets the value of the sadrzaj property.
         * 
         * @param value
         *     allowed object is
         *     {@link Amandman.GlavniDeo.Sadrzaj }
         *     
         */
        public void setSadrzaj(Amandman.GlavniDeo.Sadrzaj value) {
            this.sadrzaj = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tekst">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;choice>
         *                     &lt;element name="deo" type="{http://www.ftn.uns.ac.rs/amandman}deo"/>
         *                     &lt;element name="glava" type="{http://www.ftn.uns.ac.rs/amandman}glava"/>
         *                     &lt;element name="odeljak" type="{http://www.ftn.uns.ac.rs/amandman}odeljak"/>
         *                     &lt;element name="pododeljak" type="{http://www.ftn.uns.ac.rs/amandman}pododeljak"/>
         *                     &lt;element name="clan" type="{http://www.ftn.uns.ac.rs/amandman}clan"/>
         *                     &lt;element name="stav" type="{http://www.ftn.uns.ac.rs/amandman}stav"/>
         *                     &lt;element name="tacka" type="{http://www.ftn.uns.ac.rs/amandman}tacka"/>
         *                     &lt;element name="podtacka" type="{http://www.ftn.uns.ac.rs/amandman}podtacka"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tekst"
        })
        public static class Sadrzaj {

            @XmlElement(required = true)
            protected Amandman.GlavniDeo.Sadrzaj.Tekst tekst;

            /**
             * Gets the value of the tekst property.
             * 
             * @return
             *     possible object is
             *     {@link Amandman.GlavniDeo.Sadrzaj.Tekst }
             *     
             */
            public Amandman.GlavniDeo.Sadrzaj.Tekst getTekst() {
                return tekst;
            }

            /**
             * Sets the value of the tekst property.
             * 
             * @param value
             *     allowed object is
             *     {@link Amandman.GlavniDeo.Sadrzaj.Tekst }
             *     
             */
            public void setTekst(Amandman.GlavniDeo.Sadrzaj.Tekst value) {
                this.tekst = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;choice>
             *           &lt;element name="deo" type="{http://www.ftn.uns.ac.rs/amandman}deo"/>
             *           &lt;element name="glava" type="{http://www.ftn.uns.ac.rs/amandman}glava"/>
             *           &lt;element name="odeljak" type="{http://www.ftn.uns.ac.rs/amandman}odeljak"/>
             *           &lt;element name="pododeljak" type="{http://www.ftn.uns.ac.rs/amandman}pododeljak"/>
             *           &lt;element name="clan" type="{http://www.ftn.uns.ac.rs/amandman}clan"/>
             *           &lt;element name="stav" type="{http://www.ftn.uns.ac.rs/amandman}stav"/>
             *           &lt;element name="tacka" type="{http://www.ftn.uns.ac.rs/amandman}tacka"/>
             *           &lt;element name="podtacka" type="{http://www.ftn.uns.ac.rs/amandman}podtacka"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Tekst {

                @XmlElementRefs({
                    @XmlElementRef(name = "podtacka", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "glava", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "odeljak", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "tacka", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "stav", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "deo", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "clan", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "pododeljak", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link Podtacka }{@code >}
                 * {@link JAXBElement }{@code <}{@link Glava }{@code >}
                 * {@link JAXBElement }{@code <}{@link Odeljak }{@code >}
                 * {@link JAXBElement }{@code <}{@link Tacka }{@code >}
                 * {@link JAXBElement }{@code <}{@link Stav }{@code >}
                 * {@link JAXBElement }{@code <}{@link Deo }{@code >}
                 * {@link JAXBElement }{@code <}{@link Clan }{@code >}
                 * {@link JAXBElement }{@code <}{@link Pododeljak }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "tekst"
    })
    public static class Obrazlozenje {

        @XmlElement(required = true)
        protected String naslov;
        @XmlElement(required = true)
        protected String tekst;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekst(String value) {
            this.tekst = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="funkcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="imeIPrezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "funkcija",
        "imeIPrezime"
    })
    public static class Potpis {

        @XmlElement(required = true)
        protected String funkcija;
        @XmlElement(required = true)
        protected String imeIPrezime;

        /**
         * Gets the value of the funkcija property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunkcija() {
            return funkcija;
        }

        /**
         * Sets the value of the funkcija property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunkcija(String value) {
            this.funkcija = value;
        }

        /**
         * Gets the value of the imeIPrezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImeIPrezime() {
            return imeIPrezime;
        }

        /**
         * Sets the value of the imeIPrezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImeIPrezime(String value) {
            this.imeIPrezime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence>
     *           &lt;choice>
     *             &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *             &lt;element name="propis">
     *               &lt;complexType>
     *                 &lt;complexContent>
     *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                     &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                     &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                     &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                     &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;/restriction>
     *                 &lt;/complexContent>
     *               &lt;/complexType>
     *             &lt;/element>
     *           &lt;/choice>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "tekst",
        "propis"
    })
    public static class Uvod {

        @XmlElement(required = true, defaultValue = "\u041f\u0420\u0415\u0414\u0421\u0415\u0414\u041d\u0418\u041a\u0423 \u041d\u0410\u0420\u041e\u0414\u041d\u0415 \u0421\u041a\u0423\u041f\u0428\u0422\u0418\u041d\u0415")
        protected String naslov;
        protected String tekst;
        protected Amandman.Uvod.Propis propis;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekst(String value) {
            this.tekst = value;
        }

        /**
         * Gets the value of the propis property.
         * 
         * @return
         *     possible object is
         *     {@link Amandman.Uvod.Propis }
         *     
         */
        public Amandman.Uvod.Propis getPropis() {
            return propis;
        }

        /**
         * Sets the value of the propis property.
         * 
         * @param value
         *     allowed object is
         *     {@link Amandman.Uvod.Propis }
         *     
         */
        public void setPropis(Amandman.Uvod.Propis value) {
            this.propis = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Propis {

            @XmlAttribute(name = "vocab")
            protected String vocab;
            @XmlAttribute(name = "about")
            protected String about;
            @XmlAttribute(name = "rel")
            protected String rel;
            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the vocab property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVocab() {
                return vocab;
            }

            /**
             * Sets the value of the vocab property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVocab(String value) {
                this.vocab = value;
            }

            /**
             * Gets the value of the about property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbout() {
                return about;
            }

            /**
             * Sets the value of the about property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbout(String value) {
                this.about = value;
            }

            /**
             * Gets the value of the rel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRel() {
                return rel;
            }

            /**
             * Sets the value of the rel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRel(String value) {
                this.rel = value;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="drzava" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="organ" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="predlagac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drzava",
        "organ",
        "predlagac",
        "datum",
        "mesto"
    })
    public static class Zaglavlje {

        @XmlElement(required = true, defaultValue = "\u0420\u0415\u041f\u0423\u0411\u041b\u0418\u041a\u0410 \u0421\u0420\u0411\u0418\u0408\u0410")
        protected String drzava;
        @XmlElement(required = true, defaultValue = "\u041d\u0410\u0420\u041e\u0414\u041d\u0410 \u0421\u041a\u0423\u041f\u0428\u0422\u0418\u041d\u0410")
        protected String organ;
        @XmlElement(required = true)
        protected String predlagac;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;
        @XmlElement(required = true)
        protected String mesto;

        /**
         * Gets the value of the drzava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrzava() {
            return drzava;
        }

        /**
         * Sets the value of the drzava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrzava(String value) {
            this.drzava = value;
        }

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgan(String value) {
            this.organ = value;
        }

        /**
         * Gets the value of the predlagac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredlagac() {
            return predlagac;
        }

        /**
         * Sets the value of the predlagac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredlagac(String value) {
            this.predlagac = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the mesto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMesto(String value) {
            this.mesto = value;
        }

    }

}
