//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 10:26:08 AM CEST 
//


package rs.ac.uns.ftn.amandman;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kome">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Informacije">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="NazivPropisaKojiSeMenja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BrojeviSvihSluzbenihGlasila" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Opis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Detalji" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;choice>
 *                               &lt;element name="Clan" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                               &lt;element name="Stav" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                               &lt;element name="Tacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                               &lt;element name="Podtacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                               &lt;element name="BriseSe">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;choice>
 *                                         &lt;element name="BezReci" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;element name="Rec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;/choice>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="MenjaSe">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;choice>
 *                                         &lt;element name="tekstOdredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;sequence>
 *                                           &lt;element name="prvaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                           &lt;element name="DrugaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;/sequence>
 *                                       &lt;/choice>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Obrazlozenje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TekstObrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Predlagac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Funkcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kome",
    "opis",
    "obrazlozenje",
    "predlagac"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElement(name = "Kome", required = true)
    protected Amandman.Kome kome;
    @XmlElement(name = "Opis", required = true)
    protected Amandman.Opis opis;
    @XmlElement(name = "Obrazlozenje", required = true)
    protected Amandman.Obrazlozenje obrazlozenje;
    @XmlElement(name = "Predlagac", required = true)
    protected Amandman.Predlagac predlagac;

    /**
     * Gets the value of the kome property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Kome }
     *     
     */
    public Amandman.Kome getKome() {
        return kome;
    }

    /**
     * Sets the value of the kome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Kome }
     *     
     */
    public void setKome(Amandman.Kome value) {
        this.kome = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Opis }
     *     
     */
    public Amandman.Opis getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Opis }
     *     
     */
    public void setOpis(Amandman.Opis value) {
        this.opis = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public Amandman.Obrazlozenje getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public void setObrazlozenje(Amandman.Obrazlozenje value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Predlagac }
     *     
     */
    public Amandman.Predlagac getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Predlagac }
     *     
     */
    public void setPredlagac(Amandman.Predlagac value) {
        this.predlagac = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Informacije">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="NazivPropisaKojiSeMenja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BrojeviSvihSluzbenihGlasila" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "informacije"
    })
    public static class Kome {

        @XmlElement(name = "Naslov", required = true, defaultValue = "PREDSEDNIK NARODNE SKUPSTINE")
        protected String naslov;
        @XmlElement(name = "Informacije", required = true)
        protected Amandman.Kome.Informacije informacije;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the informacije property.
         * 
         * @return
         *     possible object is
         *     {@link Amandman.Kome.Informacije }
         *     
         */
        public Amandman.Kome.Informacije getInformacije() {
            return informacije;
        }

        /**
         * Sets the value of the informacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link Amandman.Kome.Informacije }
         *     
         */
        public void setInformacije(Amandman.Kome.Informacije value) {
            this.informacije = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="NazivPropisaKojiSeMenja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BrojeviSvihSluzbenihGlasila" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Informacije {

            @XmlElementRefs({
                @XmlElementRef(name = "BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class),
                @XmlElementRef(name = "BrojeviSvihSluzbenihGlasila", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class),
                @XmlElementRef(name = "NazivPropisaKojiSeMenja", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * {@link JAXBElement }{@code <}{@link Object }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TekstObrazlozenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "tekstObrazlozenja"
    })
    public static class Obrazlozenje {

        @XmlElement(name = "Naslov", required = true)
        protected String naslov;
        @XmlElement(name = "TekstObrazlozenja", required = true)
        protected String tekstObrazlozenja;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the tekstObrazlozenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekstObrazlozenja() {
            return tekstObrazlozenja;
        }

        /**
         * Sets the value of the tekstObrazlozenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekstObrazlozenja(String value) {
            this.tekstObrazlozenja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Detalji" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;choice>
     *                     &lt;element name="Clan" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                     &lt;element name="Stav" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                     &lt;element name="Tacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                     &lt;element name="Podtacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                     &lt;element name="BriseSe">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;choice>
     *                               &lt;element name="BezReci" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;element name="Rec" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/choice>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="MenjaSe">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;choice>
     *                               &lt;element name="tekstOdredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;sequence>
     *                                 &lt;element name="prvaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                 &lt;element name="DrugaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;/sequence>
     *                             &lt;/choice>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "detalji"
    })
    public static class Opis {

        @XmlElement(name = "Naslov", required = true, defaultValue = "AMANDMAN")
        protected String naslov;
        @XmlElement(name = "Detalji")
        protected List<Amandman.Opis.Detalji> detalji;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the detalji property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the detalji property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDetalji().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Amandman.Opis.Detalji }
         * 
         * 
         */
        public List<Amandman.Opis.Detalji> getDetalji() {
            if (detalji == null) {
                detalji = new ArrayList<Amandman.Opis.Detalji>();
            }
            return this.detalji;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;choice>
         *           &lt;element name="Clan" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *           &lt;element name="Stav" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *           &lt;element name="Tacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *           &lt;element name="Podtacka" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *           &lt;element name="BriseSe">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;choice>
         *                     &lt;element name="BezReci" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                     &lt;element name="Rec" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;/choice>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="MenjaSe">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;choice>
         *                     &lt;element name="tekstOdredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                     &lt;sequence>
         *                       &lt;element name="prvaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                       &lt;element name="DrugaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                     &lt;/sequence>
         *                   &lt;/choice>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Detalji {

            @XmlElementRefs({
                @XmlElementRef(name = "Podtacka", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "MenjaSe", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BriseSe", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Stav", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Tacka", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Clan", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link Amandman.Opis.Detalji.MenjaSe }{@code >}
             * {@link JAXBElement }{@code <}{@link Amandman.Opis.Detalji.BriseSe }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link String }
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="BezReci" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Rec" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bezReci",
                "rec"
            })
            public static class BriseSe {

                @XmlElement(name = "BezReci", defaultValue = "")
                protected String bezReci;
                @XmlElement(name = "Rec")
                protected String rec;

                /**
                 * Gets the value of the bezReci property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBezReci() {
                    return bezReci;
                }

                /**
                 * Sets the value of the bezReci property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBezReci(String value) {
                    this.bezReci = value;
                }

                /**
                 * Gets the value of the rec property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRec() {
                    return rec;
                }

                /**
                 * Sets the value of the rec property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRec(String value) {
                    this.rec = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="tekstOdredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;sequence>
             *           &lt;element name="prvaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *           &lt;element name="DrugaRec" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;/sequence>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class MenjaSe {

                @XmlElementRefs({
                    @XmlElementRef(name = "DrugaRec", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "prvaRec", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "tekstOdredbe", namespace = "http://www.ftn.uns.ac.rs/amandman", type = JAXBElement.class, required = false)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Funkcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "funkcija",
        "naziv"
    })
    public static class Predlagac {

        @XmlElement(name = "Funkcija", required = true)
        protected String funkcija;
        @XmlElement(name = "Naziv", required = true)
        protected String naziv;

        /**
         * Gets the value of the funkcija property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunkcija() {
            return funkcija;
        }

        /**
         * Sets the value of the funkcija property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunkcija(String value) {
            this.funkcija = value;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

    }

}
