//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 05:49:38 PM CEST 
//


package rs.ac.uns.ftn.amandman;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.amandman package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClanStav_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "stav");
    private final static QName _AmandmanGlavniDeoSadrzajTekstPododeljak_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "pododeljak");
    private final static QName _AmandmanGlavniDeoSadrzajTekstPodtacka_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "podtacka");
    private final static QName _AmandmanGlavniDeoSadrzajTekstClan_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "clan");
    private final static QName _AmandmanGlavniDeoSadrzajTekstGlava_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "glava");
    private final static QName _AmandmanGlavniDeoSadrzajTekstTacka_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "tacka");
    private final static QName _AmandmanGlavniDeoSadrzajTekstOdeljak_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "odeljak");
    private final static QName _AmandmanGlavniDeoSadrzajTekstDeo_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "deo");
    private final static QName _PodtackaAlineja_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "alineja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.amandman
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo }
     * 
     */
    public Amandman.GlavniDeo createAmandmanGlavniDeo() {
        return new Amandman.GlavniDeo();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj createAmandmanGlavniDeoSadrzaj() {
        return new Amandman.GlavniDeo.Sadrzaj();
    }

    /**
     * Create an instance of {@link Amandman.Uvod }
     * 
     */
    public Amandman.Uvod createAmandmanUvod() {
        return new Amandman.Uvod();
    }

    /**
     * Create an instance of {@link Amandman.Zaglavlje }
     * 
     */
    public Amandman.Zaglavlje createAmandmanZaglavlje() {
        return new Amandman.Zaglavlje();
    }

    /**
     * Create an instance of {@link Amandman.Obrazlozenje }
     * 
     */
    public Amandman.Obrazlozenje createAmandmanObrazlozenje() {
        return new Amandman.Obrazlozenje();
    }

    /**
     * Create an instance of {@link Amandman.Potpis }
     * 
     */
    public Amandman.Potpis createAmandmanPotpis() {
        return new Amandman.Potpis();
    }

    /**
     * Create an instance of {@link Pododeljak }
     * 
     */
    public Pododeljak createPododeljak() {
        return new Pododeljak();
    }

    /**
     * Create an instance of {@link Podtacka }
     * 
     */
    public Podtacka createPodtacka() {
        return new Podtacka();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Glava }
     * 
     */
    public Glava createGlava() {
        return new Glava();
    }

    /**
     * Create an instance of {@link Tacka }
     * 
     */
    public Tacka createTacka() {
        return new Tacka();
    }

    /**
     * Create an instance of {@link Stav }
     * 
     */
    public Stav createStav() {
        return new Stav();
    }

    /**
     * Create an instance of {@link Odeljak }
     * 
     */
    public Odeljak createOdeljak() {
        return new Odeljak();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst createAmandmanGlavniDeoSadrzajTekst() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst();
    }

    /**
     * Create an instance of {@link Amandman.Uvod.Propis }
     * 
     */
    public Amandman.Uvod.Propis createAmandmanUvodPropis() {
        return new Amandman.Uvod.Propis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stav }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "stav", scope = Clan.class)
    public JAXBElement<Stav> createClanStav(Stav value) {
        return new JAXBElement<Stav>(_ClanStav_QNAME, Stav.class, Clan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pododeljak }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "pododeljak", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Pododeljak> createAmandmanGlavniDeoSadrzajTekstPododeljak(Pododeljak value) {
        return new JAXBElement<Pododeljak>(_AmandmanGlavniDeoSadrzajTekstPododeljak_QNAME, Pododeljak.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Podtacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "podtacka", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Podtacka> createAmandmanGlavniDeoSadrzajTekstPodtacka(Podtacka value) {
        return new JAXBElement<Podtacka>(_AmandmanGlavniDeoSadrzajTekstPodtacka_QNAME, Podtacka.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "clan", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Clan> createAmandmanGlavniDeoSadrzajTekstClan(Clan value) {
        return new JAXBElement<Clan>(_AmandmanGlavniDeoSadrzajTekstClan_QNAME, Clan.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Glava }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "glava", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Glava> createAmandmanGlavniDeoSadrzajTekstGlava(Glava value) {
        return new JAXBElement<Glava>(_AmandmanGlavniDeoSadrzajTekstGlava_QNAME, Glava.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "tacka", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Tacka> createAmandmanGlavniDeoSadrzajTekstTacka(Tacka value) {
        return new JAXBElement<Tacka>(_AmandmanGlavniDeoSadrzajTekstTacka_QNAME, Tacka.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Odeljak }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "odeljak", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Odeljak> createAmandmanGlavniDeoSadrzajTekstOdeljak(Odeljak value) {
        return new JAXBElement<Odeljak>(_AmandmanGlavniDeoSadrzajTekstOdeljak_QNAME, Odeljak.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stav }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "stav", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Stav> createAmandmanGlavniDeoSadrzajTekstStav(Stav value) {
        return new JAXBElement<Stav>(_ClanStav_QNAME, Stav.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Deo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "deo", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Deo> createAmandmanGlavniDeoSadrzajTekstDeo(Deo value) {
        return new JAXBElement<Deo>(_AmandmanGlavniDeoSadrzajTekstDeo_QNAME, Deo.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "tacka", scope = Stav.class)
    public JAXBElement<Tacka> createStavTacka(Tacka value) {
        return new JAXBElement<Tacka>(_AmandmanGlavniDeoSadrzajTekstTacka_QNAME, Tacka.class, Stav.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Podtacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "podtacka", scope = Tacka.class)
    public JAXBElement<Podtacka> createTackaPodtacka(Podtacka value) {
        return new JAXBElement<Podtacka>(_AmandmanGlavniDeoSadrzajTekstPodtacka_QNAME, Podtacka.class, Tacka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "alineja", scope = Podtacka.class)
    public JAXBElement<String> createPodtackaAlineja(String value) {
        return new JAXBElement<String>(_PodtackaAlineja_QNAME, String.class, Podtacka.class, value);
    }

}
