//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 11:36:38 AM CEST 
//


package rs.ac.uns.ftn.amandman;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.amandman package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AmandmanGlavniDeoSadrzajTekstPodtacka_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "podtacka");
    private final static QName _AmandmanGlavniDeoSadrzajTekstClan_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "clan");
    private final static QName _AmandmanGlavniDeoSadrzajTekstTacka_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "tacka");
    private final static QName _AmandmanGlavniDeoSadrzajTekstOperacija_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "operacija");
    private final static QName _AmandmanGlavniDeoSadrzajTekstStav_QNAME = new QName("http://www.ftn.uns.ac.rs/amandman", "stav");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.amandman
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo }
     * 
     */
    public Amandman.GlavniDeo createAmandmanGlavniDeo() {
        return new Amandman.GlavniDeo();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj createAmandmanGlavniDeoSadrzaj() {
        return new Amandman.GlavniDeo.Sadrzaj();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst createAmandmanGlavniDeoSadrzajTekst() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst();
    }

    /**
     * Create an instance of {@link Amandman.Zaglavlje }
     * 
     */
    public Amandman.Zaglavlje createAmandmanZaglavlje() {
        return new Amandman.Zaglavlje();
    }

    /**
     * Create an instance of {@link Amandman.Uvod }
     * 
     */
    public Amandman.Uvod createAmandmanUvod() {
        return new Amandman.Uvod();
    }

    /**
     * Create an instance of {@link Amandman.Obrazlozenje }
     * 
     */
    public Amandman.Obrazlozenje createAmandmanObrazlozenje() {
        return new Amandman.Obrazlozenje();
    }

    /**
     * Create an instance of {@link Amandman.Potpis }
     * 
     */
    public Amandman.Potpis createAmandmanPotpis() {
        return new Amandman.Potpis();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst.Clan }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst.Clan createAmandmanGlavniDeoSadrzajTekstClan() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst.Clan();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst.Stav }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst.Stav createAmandmanGlavniDeoSadrzajTekstStav() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst.Stav();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka createAmandmanGlavniDeoSadrzajTekstTacka() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka();
    }

    /**
     * Create an instance of {@link Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka }
     * 
     */
    public Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka createAmandmanGlavniDeoSadrzajTekstPodtacka() {
        return new Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "podtacka", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka> createAmandmanGlavniDeoSadrzajTekstPodtacka(Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka value) {
        return new JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka>(_AmandmanGlavniDeoSadrzajTekstPodtacka_QNAME, Amandman.GlavniDeo.Sadrzaj.Tekst.Podtacka.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amandman.GlavniDeo.Sadrzaj.Tekst.Clan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "clan", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Clan> createAmandmanGlavniDeoSadrzajTekstClan(Amandman.GlavniDeo.Sadrzaj.Tekst.Clan value) {
        return new JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Clan>(_AmandmanGlavniDeoSadrzajTekstClan_QNAME, Amandman.GlavniDeo.Sadrzaj.Tekst.Clan.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "tacka", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka> createAmandmanGlavniDeoSadrzajTekstTacka(Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka value) {
        return new JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka>(_AmandmanGlavniDeoSadrzajTekstTacka_QNAME, Amandman.GlavniDeo.Sadrzaj.Tekst.Tacka.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "operacija", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<String> createAmandmanGlavniDeoSadrzajTekstOperacija(String value) {
        return new JAXBElement<String>(_AmandmanGlavniDeoSadrzajTekstOperacija_QNAME, String.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amandman.GlavniDeo.Sadrzaj.Tekst.Stav }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/amandman", name = "stav", scope = Amandman.GlavniDeo.Sadrzaj.Tekst.class)
    public JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Stav> createAmandmanGlavniDeoSadrzajTekstStav(Amandman.GlavniDeo.Sadrzaj.Tekst.Stav value) {
        return new JAXBElement<Amandman.GlavniDeo.Sadrzaj.Tekst.Stav>(_AmandmanGlavniDeoSadrzajTekstStav_QNAME, Amandman.GlavniDeo.Sadrzaj.Tekst.Stav.class, Amandman.GlavniDeo.Sadrzaj.Tekst.class, value);
    }

}
